spring.application.name=cixoil

spring.datasource.url=jdbc:mysql://localhost:3306/cixoil
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=q4YyIInhDc6df5095EToFSn02wNMatdLz2HJHFL2iJ3tQIwkizvmlLi43feX1sfi
jwt.expiration=3600000
jwt.refresh-expiration=604800000

spring.ai.openai.api-key=