spring.application.name=cixoil

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://cixoil-mysql-cixoil-smartflow.a.aivencloud.com:23327/defaultdb?ssl-mode=REQUIRED}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:q4YyIInhDc6df5095EToFSn02wNMatdLz2HJHFL2iJ3tQIwkizvmlLi43feX1sfi}
jwt.expiration=${JWT_EXPIRATION:3600000}
jwt.refresh-expiration=604800000

spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}
spring.ai.openai.base-url=${SPRING_AI_OPENAI_BASE_URL:https://api.groq.com/openai}
spring.ai.openai.chat.options.model=${SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL:llama-3.3-70b-versatile}

app.cloudinary.url=${APP_CLOUDINARY_URL:cloudinary://518921557231738:pKpGw1aKRm9vzvBUfa5o5oIYU3s@dmdmddtlf}